### ISSUE TITLE
Mail control as per recipient

### ISSUE THREAD

**Issue by iGaurav4** [nightcode/jmilter#11]
Is it possible to abort one particular mail for some recipient and relay it to others?

**Comment by nightcode** [comment]
Yes, you can receive list of recipients in the SMFIC_RCPT phase and modify it in the SMFIC_EOB phase.
Don't forget to set SMFIF_DELRCPT bit in actions.

**Comment by iGaurav4** [comment]
Thanks for the suggestion. I got one another issue here. Need your suggestions again. 

Is there any chance that we can embed kafka processing with milter operations? 
For example, when the mail arrives it would be listening to some kafka topic and in eom function, we can have distributed kafka processing to embed spam/phishing check functions on diff topic. And through final kafka topic, we would release/relay the mail .

**Comment by nightcode** [comment]
Yes, there is no limitation for that. You just need to consider mail processing time not to receive timeouts on the MTA side.
