### ISSUE TITLE
Integrating Milter with kafka

### ISSUE THREAD

**Issue by iGaurav4** [nightcode/jmilter#13]
In order to scale the application for analysis, we were trying to integrate kafka with milter. 
The simplest way, i could found was to send milterContext to kafka topic for further analysis and then context would be ask postfix to deliver to users or quarantine it as shown in the image. 
The initial issue in doing so, was serialization issue of MilterContext. 
@nightcode 
Could you please guide me, how can we achieve it? 

![image](https://github.com/nightcode/jmilter/assets/58951241/d2d6a292-ff57-4c2c-942b-332ac3fdf751)

**Comment by iGaurav4** [comment]
@nightcode Need your help on this.

**Comment by nightcode** [comment]
Hello, @iGaurav4 
I can suggest you do not serialize MilterContext but collect all the necessary data about the email during SMFIC_* phases and send all the collected data to Kafka in the MilterCommands.eob() method.

**Comment by iGaurav4** [comment]
![image](https://github.com/nightcode/jmilter/assets/58951241/17ba4c92-d8c9-41b2-8a5a-fe8db69e1427)

When i tried collecting all the necessary data about the email during SMFIC_* phases as EmailTopic. When this emailTopic passed to kafka, milter threads will still be in wait state to get the updated event(deliver, hold, modifications in email). 
So, one thread in wait and kafka processing, it rather add more resource utilization which can be avoided. 
What are your views in this, am i doing something wrong here ?

**Comment by nightcode** [comment]
@iGaurav4, have you tried using CompletableFuture and ThreadPools to solve your problems?
In my opinion, you should go in that direction.

**Comment by iGaurav4** [comment]
@nightcode ThreadPools would be able to solve a minor issue of scalability, while kafka could introduce vital improvement. 
Is there any chance to include kafka in the architecture?

**Comment by nightcode** [comment]
@iGaurav4, the library does not impose any restrictions on use with Kafka. The question is beyond the functionality of the library and more related to design of your application. If you need a reference implementation of using Kafka with the library, it can be discussed separately, not as part of the discussion of the library.
