### ISSUE TITLE
Protocol Version And Response Types

### ISSUE THREAD

**Issue by ozkanogun** [nightcode/jmilter#15]
Hi first of all thanks for that library. I have two questions about it,

First of all as far as i understand there are different Milter Versions Like Version 2, 6 or 8 which versions this library supports? Do you know what are the diffirences between them? In the postfix MILTER documentation there is a line " If the Postfix [milter_protocol](http://www.postfix.org/postconf.5.html#milter_protocol) setting specifies a too low version, the libmilter library will log an error message like this: " like this, because of that versions seems important to me.

My second question is how can we user Reject or TempFail ? These are inside ResponseCode enum but, inside MessageModificationService there is no methods spesified for these ResponseCodes. Do we need to develop a code something like the down below?

    MilterPacket packet = MilterPacket.builder()
        .command(SMFIR_REJECT)
        .build();

    context.sendPacket(packet);

**Comment by nightcode** [comment]
Hi @ozkanogun,
> First of all as far as i understand there are different Milter Versions Like Version 2, 6 or 8 which versions this library supports?

This library supports Milter Protocol version 6.

> Do you know what are the diffirences between them?

I don't have a document describing such differences, but I can recommend checking out the RELEASE_NOTES document (LIBMILTER related notes) from the Sendmail source code archive (https://ftp.sendmail.org).

> My second question is how can we user Reject or TempFail ?

You can find working example in https://github.com/nightcode/jmilter/blob/master/test/org/nightcode/milter/samples/TempFailMilterHandler.java.

Thank you!

**Comment by ozkanogun** [comment]
Hi @nightcode,

Thank you so much for your answers.
