### ISSUE TITLE
Reject With Reply Code And Message Question

### ISSUE THREAD

**Issue by ozkanogun** [nightcode/jmilter#16]
Hi,

I have a question about reject and tempFail. Some milter libraries have reject parameters to return reply code and message while rejection or setReply method to return a replay code and replay message. How can i do the same thing with jmilter? Is there any methods in jmilter or can you please provide me a example code for this? 

Library examples are down below,

Mailfromd : https://www.gnu.org.ua/software/mailfromd/manual/html_chapter/Tutorial.html#Simplest-Configurations 

reject(503, 5.0.0, "Need HELO command")
tempfail 450 4.7.0 "Mail sending rate exceeded.  Try again later"

sendmail libmilter : http://web.mit.edu/freebsd/head/contrib/sendmail/libmilter/docs/smfi_setreply.html 

int smfi_setreply(
	SMFICTX *ctx,
	char *rcode,
	char *xcode,
	char *message
);

python-libmilter : https://stuffivelearned.org/doku.php?id=programming:python:python-libmilter#setreply_self_rcode_xcode_msg

self.setReply(555 , '5.7.0' , 'Monkey poo has just been flung at you')

pymilter : https://github.com/sdgathman/pymilter/blob/7deec90a5983f524c308c923115e306e75581bdd/milter-nomix.py#L63

      self.setreply('550','5.7.1','Mixing internal and external TLDs')
      return Milter.REJECT

Thank you for your support.

**Comment by nightcode** [comment]
Hi,

currently you can use the following code to achieve your task:
```java
  byte[] buf = "530 5.7.0 Authentication required".getBytes(StandardCharsets.UTF_8);
  byte[] payload = new byte[buf.length + 1];
  System.arraycopy(buf, 0, payload, 0, buf.length);
  MilterPacket packet = MilterPacket.builder().command(SMFIR_REPLYCODE).payload(payload).build();

  context.sendPacket(packet);
```
I will add setReply() method for more ease of use in the next release.

Thank you.

**Comment by ozkanogun** [comment]
Thank you for your quick support :)
