### ISSUE TITLE
Please update to a higher netty version, because parts of netty have vulnerabilities.

### ISSUE THREAD

**Issue by tachtler** [nightcode/jmilter#18]
Hi Dmitry,

please update to a higher netty version, because up to **`version 4.1.109`** parts of netty have vulnerabilities.

Thank you again, for the great jmilter - I've used version 0.6. with parts of netty in version 4.1.109 - and it works great!

Best regards,
Klaus.

**Comment by nightcode** [comment]
Hi Klaus,

thank you for your attention to the project!
Version has been updated (release v0.6.1).

Best regards,
Dmitry
