### ISSUE TITLE
Send emails to spam

### ISSUE THREAD

**Issue by iGaurav4** [nightcode/jmilter#19]
This is a question, not an issue. 
I need to configure postfix or milter in a way that if some mails are spam it should be placed in spam folder of any mail client.
Is there any way to do that?

**Comment by nightcode** [comment]
You can use Apache SpamAssassin or something like this.

**Comment by iGaurav4** [comment]
@nightcode I am writing program for the same. 
I have logic to identify spam emails, but i want them to be placed in spam folder. 
So, is there anything function in postfix to do that ?
