### ISSUE TITLE
Hold Queue Override

### ISSUE THREAD

**Issue by iGaurav4** [nightcode/jmilter#20]
@nightcode 
I understand that I can use SMFIR_QUARANTINE to quarantine an email and hold it in the hold queue. However, I want to save the email (.eml file) to a separate location, independent of the Postfix instance. I'm running multiple Postfix instances and want to centralize the quarantine process. Is it possible to store the quarantined emails in a single location, such as a database or a file repository, instead of the hold queue? If so, how can I achieve this?

If such functionality is possible, how can i place the email back to active queue during the email release process ?

**Comment by nightcode** [comment]
@iGaurav4 , you can collect all the email details (envfrom, envrcpt, headers, body and e.t.c) by implementing appropriate MilterHandler functionality and send all the email data to your separate backend after EOM event.

Best regards, Dmitry

**Comment by iGaurav4** [comment]
@nightcode 
I have two issues :- 
1. Currently, quarantine emails are stored on the same server as the mail server, within a 'hold' folder. This makes it challenging to manage quarantine emails, especially when dealing with multiple domains and Postfix instances.
**Is it possible to store quarantine emails in a specific storage location based on file path? Additionally, if I have connected Postfix to a database, can I store the original EML file inside the database?**

2. If the first scenario is possible, how can I release the quarantine emails? Please provide guidance on this."

**Comment by nightcode** [comment]
Dear @iGaurav4,
all your questions are related to Postfix. It's better to ask them on specialized forums and leave this issue list for questions and bug reports related to milter protocol and jmilter library.
Thank you for understanding.
Best regards, Dmitry
