### ISSUE TITLE
Gateway bind without retry

### ISSUE THREAD

**Issue by fwiersENO** [nightcode/jmilter#22]
Hello again,

in my case, I would prefer the `MilterGatewayManager.bind()` to fail without retry/reconnect. The "use-case" here is that the application needs to either start properly or crash. The crash (or failure to start) will trigger alerts. Triggering alers is harder to do when the application is running but not yet functioning properly.

I can work with the current implementation to get the desired result. But having a, for example, `bindOnce()` method that throws an exception when the bind fails (e.g. `java.net.BindException: Address already in use`) makes for a simpler implementation.

**Comment by nightcode** [comment]
Hello,

to support your use-case the jmilter.netty.failStopMode option has been added. You need to set it into the 'true' value.

Best regards, Dmitry

**Comment by fwiersENO** [comment]
Thank you! That is very useful in my case :)
