### ISSUE TITLE
Stop non-daemon threads after "failAndStop"

### ISSUE THREAD

**Issue by fwiersENO** [nightcode/jmilter#23]
Hello,

it would be "nice to have" an option to close running non-daemon threads when a `MilterGatewayManager.bind()` fails with `failStopMode=true`. At the moment a `System.exit(1)` is needed to exit the application.

I think the running non-daemon threads are part of the `ScheduledThreadPoolExecutor`, the `serverBootstrap.config().group()`  and the `serverBootstrap.config().childGroup()`.

**Comment by nightcode** [comment]
Hello,

fixed in release 0.7.1

Best regards, Dmitry

**Comment by fwiersENO** [comment]
Thank you for the quick response and solution :)

I tested the new 0.7.1 version in my app and all non-daemon threads are indeed stopped after about 2 seconds (the Netty threads take a little while to stop). The `System.exit(1)` call is no longer required.
