### ISSUE TITLE
Stale data in context-macros?

### ISSUE THREAD

**Issue by fwiersENO** [nightcode/jmilter#25]
Hello again,

I noticed a peculiarity in the `MilterContext` data, it might be by design but I am not sure.

In my implementation, having the Postfix Queue-ID (QID) available for logging is valuable for correlation of events. This QID can be retrieved in the `AbstractMilterHandler.eoh` stage using code like:

```java
milterContext.getMacros(CommandCode.SMFIC_EOH.code()).get("i");
```

When this is executed for the first email in the `AbstractMilterHandler.header` stage, no value is returned (as expected). However, when a second email is handled (probably re-using the same connection), the QID of the previous email is returned in the `AbstractMilterHandler.header` stage.
This means that the data from the first email is kept around until it is replaced/cleared by the processing of the second email. 
I think the data from the first email should be removed as soon as processing of the second email starts?

**Comment by nightcode** [comment]
Hello @fwiersENO,

could you, please, provide logs or TCP dump of communication between MTA and milter application in such cases (for example, set log level to DEBUG for org.nightcode.milter.net.MilterGatewayManager and send me output)?

Best regards, Dmitry

**Comment by fwiersENO** [comment]
Yes, I can provide that but it will probably take a while before I have some time to collect the data.

**Comment by fwiersENO** [comment]
Some logging:
```
25 16:02:36.692 [main        ] INFO  n.e.z.milter.DkimGateway Starting gateway server at /127.0.0.1:14545 with 5 workers.
...
--- new email
25 16:12:34.342 [oll-thread-2] DEBUG n.e.z.milter.DkimMilterHandler - protocol negotiation
	MTA    { Version: 6 Actions: 000001FF ProtocolSteps: 001FFFFF}
	Milter { Version: 6 Actions: 00000001 ProtocolSteps: 0000000B}
25 16:12:34.393 [oll-thread-2] INFO  n.e.z.milter.DkimMilterHandler - QID @header-from:
25 16:12:34.394 [oll-thread-2] INFO  n.e.z.milter.DkimMilterHandler - QID @eoh: 549B4400079
-- new email
25 16:12:41.718 [oll-thread-4] INFO  n.e.z.milter.DkimMilterHandler - QID @header-from: E9E1D400079
25 16:12:41.718 [oll-thread-4] INFO  n.e.z.milter.DkimMilterHandler - QID @eoh: A2B7B400079
```

There is not much additional logging apart from the applicaiton logging. 
The "stale data" (shown in "QID @header-from: E9E1D400079") only happened after the 6th email and after the "protocol negotiation" did NOT show in logging. I think this is related to the number of workers configured for Netty - when I lower the number of workers, the "stale data" shows earlier.
I think the "protocol negotiation" confirms that this happens only when connections are re-used.

Do you still require the TCP-dump?

**Comment by nightcode** [comment]
@fwiersENO, thank you for reporting about this issue.

It was a design issue to add internal macros storage to the MilterContext. Such things should be in the user code, for sure.
I added MilterContext.clearMacros() method in the version v0.7.3 in case of you still want to use internal macros Map form the Context.
In the version v0.8 all methods, related to store macros data in the context have been removed. All macros data can be received and processed by implementing method "macro(MilterContext context, int type, Map<String, String> macros)" of AbstractMilterHandler. I strongly recommend you  migrate to the version v0.8.

Best regards, Dmitry

**Comment by fwiersENO** [comment]
@nightcode Thank you for your efforts once again :)

I used the new v0.8 and can confirm it works as expected. E.g. getting the queue-id:
```java
    @Override 
    public void macro(MilterContext context, int type, Map<String, String> macros) {
        
        // Retrieve postfix queue-id, only available at and after EOH.
        if (type == CommandCode.SMFIC_EOH.code() && macros != null) {
            String qid = macros.get("i");
            // more code ...
        }
    }
```
