### ISSUE TITLE
Any plans to implement a milter client ?

### ISSUE THREAD

**Issue by chibenwa** [nightcode/jmilter#7]
This library allows to build a milter service that can be connected to a mail server.

I believe it would be useful to also provide a tiny milter client library.

Benefits:
  - allows the milter service writters to writte integration tests
  - allows to query stuff like RSpamd from raw java code without the needs of using an email server
  - And allows java based email servers to call milters

I would be interested to use such a jmilter client library in conjunction with https://james.apache.org for instance.

**Comment by nightcode** [comment]
Sounds reasonable. Developing a prototype of such a client will not take much time.

**Comment by nightcode** [comment]
Milter client implemented in the release v0.4.1.
