### ISSUE TITLE
Quarantine emails

### ISSUE THREAD

**Issue by iGaurav4** [nightcode/jmilter#9]
We are trying to implement quarantine functionality for the incoming mails using postfix milter.
We have used [smfi_quarantine](https://pythonhosted.org/pymilter/milter_api/smfi_quarantine.html) function to quarantine e-mail, but we are facing some issues. 
Could you please help us in below points : - 

How can we trace the quarantine mails ? 
I have checked in /var/spool/postfix/hold there are no mails in hold state. Where does the quarantine mails got stored? 
Do we any milter functionality to release the mail ? 
If mails are not present in hold queue, then we are unable to release the mail using postsuper or postqueue. How can we release the mail? 
Also, how can we abort the mail?
If we want to save the quarantine mail details in mongoDb, can we do that ?

**Comment by iGaurav4** [comment]
@nightcode 
Thanks for the response. 
We have implemented the quarantine with the help of test cases. Which I had missed. 

Now, the only issue left with us is release the mail from postfix hold/quarantine queue. 

Could you please help how to release those mail using jmilter ? 

Thanks a lot for all the help.

**Comment by nightcode** [comment]
Unfortunately, there is no way to use milter functionality to release queued messages in Postfix.

**Comment by nightcode** [comment]
@iGaurav4 
You can get a Postfix QueueID from 'i' macros.

**Comment by iGaurav4** [comment]
Thanks @nightcode for the help. 
How can we extract the attachments from the email ?

**Comment by nightcode** [comment]
You can receive full message body with all attachments during 'body' stage (as one or more body chunks, depends on the size of message and attachments).On 14 Jul 2022 21:46, iGaurav4 ***@***.***> wrote:
Thanks @nightcode for the help.
How can we extract the attachments from the email ?

**Comment by iGaurav4** [comment]
@nightcode 
Do we have any function to notify sender/receivers when their email have been quarantined using jmilter ?

**Comment by nightcode** [comment]
Yes, you can implement your notification logic in MilterHandler. There is no any kind of specific limitation.

**Comment by iGaurav4** [comment]
@nightcode If one email is having multiple recipients, in such cases milter/postfix will consider single email thread or multiple threads. 
Recipients might be of different domains.
Could you please enlighten us with these queries?

**Comment by nightcode** [comment]
@iGaurav4 , if I understood your question correctly, you will receive all the recipients during one milter session.

**Comment by iGaurav4** [comment]
@nightcode You mean there will be one milter session irrespective of number of recipients. 
Even single recipients in an email will create 1 session and multiple recipients will create 1 session.
Did i understood it correctly?
